### ISSUE TITLE
myapp fab create-admin报错

### ISSUE THREAD

**Issue by tianyunzqs** [tencentmusic/cube-studio#105]
系统：Ubuntu16.04.7
现象：kubeflow-dashboard启动不了
具体原因：myapp fab create-admin报错
![image](https://user-images.githubusercontent.com/23567448/195492919-30dd73fb-28e0-4952-9c97-334b93d80530.png)

**Comment by tianyunzqs** [comment]
是不是可能跟python版本和依赖包版本有关呢？  系统版本也可能是一个原因

**Comment by cyxnzb** [comment]
可以尝试下升级系统版本

**Comment by tianyunzqs** [comment]
已解决，本质原因是操作系统不支持AVX指令集（支持AVX2，不支持AVX也不行），导致flask调用numpy出行core dumped错误。
解决方案：在自己机器上重新编译numpy，不能直接pip安装
