### ISSUE TITLE
Use online development - "notebook" to find problems

### ISSUE THREAD

**Issue by dlimeng** [tencentmusic/cube-studio#123]
1.添加notebook ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-bigdata 镜像可以使用
2.续期到期后，镜像自动挂了，状态显示unknown
3.然后点击续期，重置reset ，镜像重启失败了，状态显示Failed

1. Add notebook ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-bigdata image can be used
2. After the renewal expires, the mirror automatically hangs up, and the status shows unknown
3. Then click Renew, reset reset, the mirror restart failed, and the status shows Failed

<img width="1779" alt="image" src="https://user-images.githubusercontent.com/16789827/200221110-f5967022-d030-46df-8158-528d4504bb96.png">

**Comment by data-infra** [comment]
管理员可以 点进去“状态”  然后进入到k8s dashboard 查看原因。有可能是
1、因为机器原因pod启动不起来，
2、资源配置太小
3、/mnt/$username/init.sh下面初始化内容太耗资源 把notebook打挂了
