### ISSUE TITLE
关于将Cube studio嵌入其他云平台的cookie的作用域问题

### ISSUE THREAD

**Issue by bumblebeeK** [tencentmusic/cube-studio#126]
现有返回的cookie的domain是子域名的，如果通过iframe将cube嵌入到其它的云平台上，cookie将会产生跨域问题，是否可以考虑增加一个配置来修改flask返回的cookie的作用域呢？

**Comment by data-infra** [comment]
#7a4d873e552f8605196dcfcaea5e85e09b524902
更新到2022.09月份版本中。修改config.py 添加COOKIE_DOMAIN='.你的域名后缀'
