### ISSUE TITLE
80端口被占用，如何修改为其他端口

### ISSUE THREAD

**Issue by Consinv** [tencentmusic/cube-studio#128]
修改gateway文件无效
![image](https://user-images.githubusercontent.com/44658996/201837640-3fd6c92e-8a29-48a9-a1b1-c6d007b525a1.png)

**Comment by data-infra** [comment]
gateway  为识别istio-system/svc/istio-ingressgateway的port所对应的targetPort，并在istio-ingressgateway中监听这个targetPort。如果需要更换为其他端口，
1、可以将port 更改为其他端口，同时将gateway中的端口也更改为其他对应的端口。
2、或者istio-ingressgateway服务使用nodeport的模式
