### ISSUE TITLE
内部服务，添加云原生服务，修改默认端口80为30021,会导致首页打不开

### ISSUE THREAD

**Issue by gilearn** [tencentmusic/cube-studio#13]
![image](https://user-images.githubusercontent.com/107160156/172747562-826faadc-0093-4c7d-80f6-5daa90bb00e8.png)

**Comment by data-infra** [comment]
内部服务关口和首页本身并没有关系。这里服务的端口也只是pod的端口，本身也不对外暴露，所以这里没有理解到
