### ISSUE TITLE
单机版本部署rancher后，无法访问web页面，日志出现error syncing 'validating-webhook-configuration': handler need-a-cert

### ISSUE THREAD

**Issue by palpitate97** [tencentmusic/cube-studio#134]
存在一些依赖出现
2022/11/22 08:51:03 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/11/22 08:51:03 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/11/22 08:51:33 [ERROR] error syncing 'mutating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2022/11/22 08:51:33 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing

**Comment by data-infra** [comment]
如果istio部署有问题，对于k8s 1.21+以上的版本。使用如下命令修复
```
kubectl delete -f istio/install.yaml
kubectl apply -f istio/install-1.15.0.yaml
kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalIPs":["'"xx.xx.xx.xx"'"]}}'
```
