### ISSUE TITLE
操作中通过更多中的删除无法删除，但通过批量操作中的删除可以进行删除(默认存在的删不了)

### ISSUE THREAD

**Issue by SimpleCavaliers** [tencentmusic/cube-studio#137]
![1](https://user-images.githubusercontent.com/36783844/204147533-194a76a2-1bb1-4e0e-9400-24cdce00015d.png)
![2](https://user-images.githubusercontent.com/36783844/204147541-d97cc19b-8ff9-49c7-a1ae-223a7fd64d62.png)

**Comment by SimpleCavaliers** [comment]
有些模块批量删除显示操作成功，但是页面上依然存在。
![1](https://user-images.githubusercontent.com/36783844/204181530-968f1bcb-48aa-46a1-ba95-310db7b30503.png)
![2](https://user-images.githubusercontent.com/36783844/204181535-556372fe-e52d-40bf-b9d8-8326e18b5df0.png)

**Comment by data-infra** [comment]
可以查看下后台日志
