### ISSUE TITLE
样例任务流运行完成后，中间过程yolov3的容器没有被清除？

### ISSUE THREAD

**Issue by SimpleCavaliers** [tencentmusic/cube-studio#138]
![1](https://user-images.githubusercontent.com/36783844/204204889-d5f21984-5722-4b22-8146-2079ca0e9071.png)
![2](https://user-images.githubusercontent.com/36783844/204204897-c3712e3c-5b1b-4ad1-9195-0533b13dc524.png)

**Comment by data-infra** [comment]
要三个小时以后才会被自动清理。这样能有时间查看报错或者中间日志
