### ISSUE TITLE
小bug：数据开发-任务ETL-任务流列表中的任务名称取值错误

### ISSUE THREAD

**Issue by AsteriaChiu** [tencentmusic/cube-studio#139]
![image](https://user-images.githubusercontent.com/25149522/204247337-66c4d10b-1de7-46e5-9eb8-7fc572e42021.png)
当前的任务流名称不是取的「名称」，而是「描述」
![image](https://user-images.githubusercontent.com/25149522/204247528-57972a69-7b91-409d-9899-cc60ffc892da.png)

**Comment by data-infra** [comment]
是这样的，显示中文描述更方便
