### ISSUE TITLE
能否隔离部署？也就是说，各个服务的镜像不会自动拉取更新。

### ISSUE THREAD

**Issue by gilearn** [tencentmusic/cube-studio#14]
自动拉取更新镜像，会导致很多问题，比如，正在研究某功能，正在运行某作业。镜像更新了，镜像有点问题或者跟本环境有不适配的地方。会导致某些功能异常，进而导致研究无法进行。

**Comment by data-infra** [comment]
现在平台里面：平台需要的组件一般已经设置为IfNotPresent，对于可能需要更新的部分，比如web前后的镜像，任务模板镜像，这种在开发时可能会持续更新的镜像使用的拉取策略
