### ISSUE TITLE
单机部署rancher之后进不去web页面

### ISSUE THREAD

**Issue by Dmayset** [tencentmusic/cube-studio#143]
运行完部署rancher命令后，进不去web页面，查看了docker相关日志后，发现下面错误 k3s exited with: exit status 1：

2022/11/30 15:03:45 [INFO] Listening on /tmp/log.sock 
2022/11/30 15:03:45 [INFO] Running etcd --data-dir=management-state/etcd --heartbeat-interval=500 --election-timeout=5000
2022/11/30 15:03:54 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/11/30 15:03:56 [INFO] Waiting for server to become available: the server is currently unable to handle the request
2022/11/30 15:03:58 [INFO] Waiting for server to become available: the server is currently unable to handle the request
2022/11/30 15:04:00 [FATAL] k3s exited with: exit status 1
2022/11/30 15:04:01 [INFO] Rancher version v2.5.2 (499387578) is starting
2022/11/30 15:04:01 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:3 Agent:false Features:}

**Comment by data-infra** [comment]
reset_docker.sh全部清理掉后，重新部署。记得提前拉取rancher镜像和放开防火墙

在部署k8s后，记得配置成单机高可用

https://github.com/tencentmusic/cube-studio/wiki/%E4%BD%BF%E7%94%A8rancher%E8%87%AA%E5%BB%BAk8s%E9%9B%86%E7%BE%A4
