### ISSUE TITLE
访问demo地址http://www.data-master.net:8880/frontend/报错

### ISSUE THREAD

**Issue by mingbozhang** [tencentmusic/cube-studio#146]
![image](https://user-images.githubusercontent.com/15163626/204990892-a3bcc07b-0165-45b6-b4c9-382345433a1b.png)

**Comment by data-infra** [comment]
需要github登录，有时网络问题获取不到，可以多试一试

**Comment by jnhzzzk** [comment]
同样的问题

**Comment by chain312** [comment]
同样的问题

**Comment by little-seven0727** [comment]
![image](https://user-images.githubusercontent.com/127741121/224679851-477367df-5a24-49d0-a79e-7f64abb051c1.png)

demo地址报错
