### ISSUE TITLE
用户认证系统的问题

### ISSUE THREAD

**Issue by dhiyu** [tencentmusic/cube-studio#147]
如题，管理员创建账号不仅无法填写和修改密码，而且创建之后只要输入该用户名登录则显示Internal Server Error。
![image](https://user-images.githubusercontent.com/37993729/205055270-594e5d79-d0f1-4d1c-a0cc-556cb1e95cb9.png)
但是更诡异的是没有创建账号但是在登录页面随意输入都会创建一个新账号且登录成功。
![image](https://user-images.githubusercontent.com/37993729/205055422-7da2601d-3aae-4970-81a6-f54ffa2bae29.png)
![image](https://user-images.githubusercontent.com/37993729/205055480-2683867a-a8df-4412-9347-b9bc3549fb4c.png)

**Comment by data-infra** [comment]
登录只要是新用户名，会自动创建账号。用户个人登录以后在右上角个人页面可以修改密码。 管理员创建方法也是直接新账号登录

**Comment by dhiyu** [comment]
感谢回复！后续是否会考虑完善权限管理和登录/注册系统呢？
