### ISSUE TITLE
更改前端UI界面，没有反应

### ISSUE THREAD

**Issue by YuchaoLau** [tencentmusic/cube-studio#148]
前后端代码均在容器中运行，使用docker-compose启动。

我想要添加一些页面新的功能，比如下图中，在【更多】里添加新的操作。
![image](https://user-images.githubusercontent.com/54919837/205475950-452668bf-f227-4782-97e3-1b3f1bbc7498.png)

我在ADUGTemplate中修改，界面显示没有任何变化
![image](https://user-images.githubusercontent.com/54919837/205475837-cbcc366d-9930-4b66-93df-edd89dbab24a.png)

添加或更改前端页面，具体怎么操作？

**Comment by data-infra** [comment]
这个是由后台来实现的。需要对应的视图里面添加action函数

**Comment by YuchaoLau** [comment]
> 这个是由后台来实现的。需要对应的视图里面添加action函数

谢谢您的解答。action函数应该算是后端的接口，我想在这里添加一个上传和下载数据集的功能，这应该还需要写一些前端界面；我不知道这个框架怎么改前端界面，将前后端对应上。
