### ISSUE TITLE
执行start.sh报错

### ISSUE THREAD

**Issue by zzzzzzyzz** [tencentmusic/cube-studio#149]
请问一下这个报错是什么原因呢

**Comment by zzzzzzyzz** [comment]
goroutine 1 [running] 
k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev3.handleErr(0xc0007611e8)

**Comment by zzzzzzyzz** [comment]
就是执行这个，cube-studio一直起不来，http://ip也打不开（我这边好像图片发不了）

**Comment by zzzzzzyzz** [comment]
执行的这个怎么解决呢，执行sh statrt.sh ip

**Comment by zzzzzzyzz** [comment]
还有个问题就是，我的ip都是用的内网ip，没有公网，这是不是原因呢

**Comment by data-infra** [comment]
与公网没关系。目前解决了么？可以购买公有云测试下，参考下社区的文章

**Comment by zzzzzzyzz** [comment]
已经解决了，谢谢
