### ISSUE TITLE
rancher部署的时候不成功，等了很久一直失败

### ISSUE THREAD

**Issue by chendile** [tencentmusic/cube-studio#16]

**Comment by data-infra** [comment]
1、有可能镜像不全，那样就得拉取镜像，所以先把镜像拉取完整
![image](https://user-images.githubusercontent.com/20157705/173190114-84c16874-5db8-43cd-9ada-424c355b4442.png)
2、有可能docker上的容器有问题，reset_docker 以后记得docker ps 看看是不是里面的镜像都空了。如果没空重启下机器。再reset_docker，然后重新安装

**Comment by data-infra** [comment]
参考wiki中“使用rancher自建k8s集群”其中包含rancher可能遇到的问题
