### ISSUE TITLE
运行dockerfile-base时报错

### ISSUE THREAD

**Issue by SimpleCavaliers** [tencentmusic/cube-studio#160]
![1](https://user-images.githubusercontent.com/36783844/215336731-1ae02d21-b202-401c-b71d-33188a494dcb.png)
在文件中执行到apt-get update -y时报错，在网上查了其他方法如修改sources.list依然报错，貌似是Debian的问题。是否可以更换python基础镜像

**Comment by data-infra** [comment]
新版本更新为国内源
