### ISSUE TITLE
stat /data/k8s/kubeflow/pipeline/workspace: no such fire or  directory

### ISSUE THREAD

**Issue by whk06** [tencentmusic/cube-studio#164]
pipeline和jupyter两个namespace内的pod均提示“stat /data/k8s/kubeflow/pipeline/workspace: no such fire or  directory"，请问该如何调整呢？现在均卡在ContainerCreating阶段。 @data-infra

**Comment by data-infra** [comment]
rancher yaml中要挂载/data:/data，要重启kubelet，  docker restart kubelet  验证kubelet 容器中是否是主机上的/data/k8s/kubeflow/pipeline/workspace 目录

**Comment by chengadmin80** [comment]
您好，我也出现了这样的问题，请问要怎么解决了，上面说的rancher yaml中要挂载/data:/data，没看懂
