### ISSUE TITLE
start.sh运行报错 E0303 10:48:29.954108 3543598 memcache.go:255] couldn't get resource list for custom.metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by GQ0308** [tencentmusic/cube-studio#166]
系统环境 单机CentOS 7.9，Docker 20.10.7, Rancher 2.5.2, K8S 1.18

根据文字和视频教程，走到start.sh脚本时报错，于是清理环境后逐条运行，在执行以下命令时发生错误
```
kubectl create clusterrole frameworkbarrier --verb=get,list,watch --resource=frameworks

E0303 10:48:29.954108 3543598 memcache.go:255] couldn't get resource list for custom.metrics.k8s.io/v1beta1: Got empty response for: custom.metrics.k8s.io/v1beta1
clusterrole.rbac.authorization.k8s.io/frameworkbarrier created
```
![image](https://user-images.githubusercontent.com/11734538/222622919-86cbf575-418e-450e-b0f3-b2d45474c44f.png)

通过kubectl get pods -A查看时也有同样的提示。

因不熟悉K8S，主要靠Wiki、视频和README的指导，多次尝试清空环境、执行均未部署成功。

**Comment by data-infra** [comment]
framework 不再使用
