### ISSUE TITLE
如何进行算子的编排

### ISSUE THREAD

**Issue by QinboZhao** [tencentmusic/cube-studio#167]
如何实现编排输入输出的衔接，而不是通过指定同一个文件的方式。例如Input parameters，Input artifacts,Output parameters。能通过可视化方式实现变量的衔接吗。

**Comment by data-infra** [comment]
目前没有，在考虑中

**Comment by lkad** [comment]
目前用的argo workflows就是使用的输入输出的的参数衔接。 确实很需要此功能.

**Comment by data-infra** [comment]
目前仅在企业版中支持
