### ISSUE TITLE
服务化->服务上线 部署之后，无法访问服务

### ISSUE THREAD

**Issue by 825200719** [tencentmusic/cube-studio#169]
阿里云服务器部署成功之后，运行示例：图像预测+物体检测+视频跟踪，示例运行成功，部署上线后，通过IP无法访问服务（502），查看日志，并没有报错信息。

![image](https://user-images.githubusercontent.com/31305021/224653495-05a52bc5-1902-42e5-818e-81b9f1556af2.png)

**Comment by kwuliang** [comment]
老哥怎么解决的，我看服务端口都暴露出来了，就是拒绝访问

**Comment by TangiSingle** [comment]
我也是拒绝访问，怎么解决的o(╥﹏╥)o
