### ISSUE TITLE
部署以后，cert-manager   pod 不正常 ，所以istio的pod组件缺少挂载

### ISSUE THREAD

**Issue by chendile** [tencentmusic/cube-studio#17]

**Comment by data-infra** [comment]
一般报错显示
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/20157705/173190515-32b650a4-8f3b-4da3-918c-5d078495290e.png">

cert-manger报错是因为需要部署的k8s的kube-api添加启动参数。参考https://github.com/tencentmusic/cube-studio/tree/master/install/kubernetes/kubeflow/v1.2.0

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/20157705/173190551-c4ac2524-84e0-4f36-a2b6-30a0e4c504c8.png">
