### ISSUE TITLE
机器重启或者机器上的docker 服务 重启后rancher web界面打不开了。

### ISSUE THREAD

**Issue by chendile** [tencentmusic/cube-studio#18]

**Comment by data-infra** [comment]
重启机器，或者重启机器上的docker服务，rancher server这个pod会启动失败，一直报wait k3s start的错误。
试试 单节点高可用的方案：https://github.com/tencentmusic/cube-studio/tree/master/install/kubernetes/rancher#%E5%8D%95%E8%8A%82%E7%82%B9%E7%9A%84%E9%85%8D%E7%BD%AE%E9%AB%98%E5%8F%AF%E7%94%A8

**Comment by cyxnzb** [comment]
最新版的rancher貌似没这个问题，但是我不确定
