### ISSUE TITLE
如何修改notebook的镜像

### ISSUE THREAD

**Issue by chendile** [tencentmusic/cube-studio#19]

**Comment by data-infra** [comment]
notebook的镜像和显示，都是在config.py文件里面配置的。

NOTEBOOK_IMAGES=[
    ['ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-cpu-base', 'vscode（cpu）'],
    ['ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-gpu-base', 'vscode（gpu）'],
    ['ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-cpu-base', 'jupyter（cpu）'],
    ['ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-gpu-base','jupyter（gpu）'],
    ['ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-cpu-1.0.0', 'jupyter（tensorboard）'],
]
在这里面可以添加修改自己的notebook镜像，但是要注意名称中记得携带vscode和jupyter的字眼，因为在代码中识别字符串决定镜像的启动方式，

在k8s中config.py被创建为infra命名空间下kubeflow-dashboard-config的configmap，需要修改后更新到这里或者，直接修改这里。  修改后重启dashboard的pod就可以了
