### ISSUE TITLE
如何在之前notebook镜像上添加插件，并且重启后生效

### ISSUE THREAD

**Issue by chendile** [tencentmusic/cube-studio#20]

**Comment by data-infra** [comment]
在平台启动后的notebook里面安装插件是不会被记忆，也不会传播给其他人的，毕竟你的pod重启后环境就丢失了。只能重新构建notebook的镜像。
这里是jupyter的构建镜像：https://github.com/tencentmusic/cube-studio/tree/master/images/jupyter-notebook
这里是vscode的构建镜像：https://github.com/tencentmusic/cube-studio/tree/master/images/theia

如果不知道如何使用dockerfile构建notebook镜像时安装插件。也可以在本地docker run一个 本地的notebook容器，然后本地打开notebook的web，在里面操作，安装插件。最后再 把容器commit成镜像。
