### ISSUE TITLE
 在containerd的k8s集群，Pipeline需要挂载本地的docker.sock， 我想改用dind， 但是还是有点问题， 求助一下

### ISSUE THREAD

**Issue by shenbinglife** [tencentmusic/cube-studio#201]
![616f61c264c39692434dcd730bfba8d](https://github.com/tencentmusic/cube-studio/assets/16119667/a1412923-0115-462f-939e-88cb80e165e8)
我这边要怎么移除这个wait Pod ？

**Comment by data-infra** [comment]
新版本已经支持containerd
