### ISSUE TITLE
数据集 批量导入后报错，显示页面有问题

### ISSUE THREAD

**Issue by miracletiger** [tencentmusic/cube-studio#204]
![image](https://github.com/tencentmusic/cube-studio/assets/17160259/fdd02297-dbf2-45ae-b25f-49376c587465)
数据集 批量导入后报错，显示页面有问题
![image](https://github.com/tencentmusic/cube-studio/assets/17160259/d3ea9f47-3869-46bf-a46d-0cb24f9add44)

**Comment by InvincibleMinions** [comment]
请问有解决吗，我也遇到这个问题

**Comment by data-infra** [comment]
新版本发布，修复了这个问题
