### ISSUE TITLE
安装问题关于已存在kubeflow prometheus

### ISSUE THREAD

**Issue by 631068264** [tencentmusic/cube-studio#205]
针对 现有

kubeflow1.6  
k8s 1.22.9
rancher2.6.5  + 再集群已经安装Monitoring (100.2.0+up40.1.2) 

那运行start.sh 要怎么改？

还是要卸载原来的？

**Comment by gxin0426** [comment]
建议将kubeflow相关组件卸载(包括crd), start.sh 中注释掉monitoring部分代码，再执行start.sh 脚本
