### ISSUE TITLE
添加notebook后，平台页面无法打开

### ISSUE THREAD

**Issue by skynewborn** [tencentmusic/cube-studio#206]
首先完成单机部署，服务地址为http://xxx.xxx.xxx.xxx。
由于该地址为内网地址，无法直接在浏览器访问，因此使用Nginx反向代理到该服务地址。输入域名后可以打开平台页面。
创建notebook，点击保存按钮之后，刷新页面，结果为404。
从服务状态来看，运行是正常的，但不知为何创建notebook之后，平台页面就无法显示了。希望能在文档中增加反向代理的正确配置方式说明。

**Comment by data-infra** [comment]
域名访问需要根据https://github.com/tencentmusic/cube-studio/blob/master/install/kubernetes/gateway.yaml  进行修复

**Comment by zhuqiming678** [comment]
please help for details, how to use [gateway.yaml](https://github.com/tencentmusic/cube-studio/blob/master/install/kubernetes/gateway.yaml)

**Comment by zhuqiming678** [comment]
> 首先完成单机部署，服务地址为[http://xxx.xxx.xxx.xxx。](http://xxx.xxx.xxx.xxx%E3%80%82) 由于该地址为内网地址，无法直接在浏览器访问，因此使用Nginx反向代理到该服务地址。输入域名后可以打开平台页面。 创建notebook，点击保存按钮之后，刷新页面，结果为404。 从服务状态来看，运行是正常的，但不知为何创建notebook之后，平台页面就无法显示了。希望能在文档中增加反向代理的正确配置方式说明。

这个问题解决了吗？我也遇到了。

**Comment by zhuqiming678** [comment]
thanks， I have solved this problem. BY add host(example, music.tencent.com.cn) in [gateway.yaml](https://github.com/tencentmusic/cube-studio/blob/master/install/kubernetes/gateway.yaml)
