### ISSUE TITLE
批量导出报错

### ISSUE THREAD

**Issue by InvincibleMinions** [tencentmusic/cube-studio#216]
![Snipaste_2023-12-12_22-20-38](https://github.com/tencentmusic/cube-studio/assets/153627466/a3e8dc2d-3af1-4035-80f7-34421bfa1c7d)
![Snipaste_2023-12-12_22-20-15](https://github.com/tencentmusic/cube-studio/assets/153627466/b628f52f-42bf-4199-b8d3-3a8720fb65c6)

**Comment by data-infra** [comment]
新版本已经修复
