### ISSUE TITLE
dataset模板导入数据提示not found for url

### ISSUE THREAD

**Issue by InvincibleMinions** [tencentmusic/cube-studio#217]
![Snipaste_2023-12-14_10-05-58](https://github.com/tencentmusic/cube-studio/assets/153627466/0cd70919-6da0-4b3b-bc6a-0425e92cfa5c)
![Snipaste_2023-12-14_10-05-33](https://github.com/tencentmusic/cube-studio/assets/153627466/740de707-0db4-4d2d-b946-72bcc941248c)

**Comment by data-infra** [comment]
新版本发布修复了
