### ISSUE TITLE
PODs - Kubeflow-dashbard 无法启动 报kubeflow.ab_permission_view_role不存在

### ISSUE THREAD

**Issue by dengdongshan** [tencentmusic/cube-studio#218]
Kubeflow-dashbard 无法启动 报kubeflow.ab_permission_view_role不存在，POD-mysql中缺少该表

![image](https://github.com/tencentmusic/cube-studio/assets/46281850/df82bdf3-5883-492b-bd8c-77309ddef256)

raise errorclass(errno, errval)
Fri, Dec 15 2023 11:09:09 pm | sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'kubeflow.ab_permission_view_role' doesn't exist")
Fri, Dec 15 2023 11:09:09 pm | [SQL: SELECT ab_permission_view.id AS ab_permission_view_id, ab_permission_view.permission_id AS ab_permission_view_permission_id, ab_permission_view.view_menu_id AS ab_permission_view_view_menu_id
Fri, Dec 15 2023 11:09:09 pm

![image](https://github.com/tencentmusic/cube-studio/assets/46281850/17bddfb1-4585-4612-85c7-d217a041e400)

**Comment by data-infra** [comment]
删除数据库，重启infra空间 mysql pod和infra空间 kubeflow-dashboard pod

**Comment by dengdongshan** [comment]
已解决：
1. rm -rf /data/k8s/infra/mysql
2. kubectl rollout restart deployment mysql -n infra
3. kubectl rollout restart deployment kubeflow-dashboard -n infra
