### ISSUE TITLE
cube bug

### ISSUE THREAD

**Issue by githubgtl** [tencentmusic/cube-studio#219]
我们发现登录cube平台之后，如果同一个浏览器上有2个以及以上的页面，在其中一个页面退出，在其他页面刷新直接报错500

**Comment by data-infra** [comment]
新版本发布修复了，其他页面会让登录

**Comment by githubgtl** [comment]
> 新版本发布修复了，其他页面会让登录
请问您这边具体在那个文件修改了，我们升级cube版本很麻烦
