### ISSUE TITLE
异构算力支持？

### ISSUE THREAD

**Issue by jeremyjiao** [tencentmusic/cube-studio#221]
看描述可以支持海光DCU和华为NPU，但是看扩容的时候还是要基于nvidia-docker2，那这样是否只是限定了只可以扩容GPU？

是否存在异构算力统一管理的可能性，如一个集群内包括了NPU和GPU两种架构的计算资源，可以统一管控，不一定统一调度。

谢谢！

**Comment by data-infra** [comment]
目前只有企业版支持国产gpu
