### ISSUE TITLE
【模型训练】 创建的任务模板无法删除

### ISSUE THREAD

**Issue by adgers** [tencentmusic/cube-studio#222]
![image](https://github.com/tencentmusic/cube-studio/assets/52065423/01ab9021-1b80-4f4b-89f2-f3e91f972fd9)

**Comment by adgers** [comment]
有任务流绑定了这个任务模板， 删除任务模板出错。

**Comment by data-infra** [comment]
有相关其他数据绑定是没法删除的，不然之前的任务流和任务就没法运行了，不想要了的任务模板可以改为alpha状态
