### ISSUE TITLE
启动以后【标注平台】功能入口是disabled的状态

### ISSUE THREAD

**Issue by HeavenDuke** [tencentmusic/cube-studio#227]
情况如下图所示：

![QQ截图20240123171256](https://github.com/tencentmusic/cube-studio/assets/6873217/fe84f118-414d-4109-bc29-157d01926742)

在代码库里搜索只搜到了一个virtualservice与label-studio有关系，请问现在这块的集成工作完成了吗？如果没有完成，应该怎么独立部署？

**Comment by data-infra** [comment]
禁用的功能为目前企业版才有
