### ISSUE TITLE
项目空间-资源配置模块为disabled状态

### ISSUE THREAD

**Issue by realtyz** [tencentmusic/cube-studio#228]
![screenshot](https://github.com/tencentmusic/cube-studio/assets/12122690/dcf71bcb-ccc6-4278-9a42-2d4ff1a7ce15)

rancher k8s 单机部署完成后，项目空间的资源配置模块为disabled状态。
查看前端代码发现菜单栏中将这两个item都禁用了，目前该功能无法使用吗？

**Comment by data-infra** [comment]
禁用的功能为企业版才有
