### ISSUE TITLE
私有仓库镜像节点无法运行 failed to look-up entrypoint/cmd for image \"172.40.20.82:8443/aiclube/model_download\"

### ISSUE THREAD

**Issue by gfoxlin** [tencentmusic/cube-studio#229]
1.私有仓库Harbor v2.8.2-d4c34dc 建立的项目是Public 
2.自建测试 Deployment kubectl运行镜像下载成功（**排除镜像下载问题** - 本地存在该镜像也有下面的问题）
3.【步骤】将model-download push到私有仓库，》添加本地镜像到系统 》修改‘数据导入导出-model-download’的镜像 》任务流拖出模型导入组件保存 》 运行【必现】

"test-pipeline-misl-ef38-984341727": {
                "boundaryID": "test-pipeline-misl-ef38",
                "displayName": "model-download-1707182945889",
                "finishedAt": "2024-02-06T01:29:12Z",
                "id": "test-pipeline-misl-ef38-984341727",
                "message": "task 'test-pipeline-misl-ef38.model-download-1707182945889' errored: **failed to look-up entrypoint/cmd for image \"172.40.20.82:8443/aiclube/model_download\", you must either explicitly specify the command,** or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary: Get \"https://172.40.20.82:8443/v2/\": http: server gave HTTP response to HTTPS client",
                "name": "test-pipeline-misl-ef38.model-download-1707182945889",
                "phase": "Error",
                "progress": "0/1",
                "startedAt": "2024-02-06T01:29:12Z",
                "templateName": "model-download-1707182945889",
                "templateScope": "local/test-pipeline-misl-ef38",
                "type": "Pod"
            }

**Comment by data-infra** [comment]
注册模板时，添加上启动命令
