### ISSUE TITLE
使用sealos部署的k8s单机，在点击k8s Dashboard、Grafana以及进入到notebook时都会出现404错误

### ISSUE THREAD

**Issue by PythonLover-Sam** [tencentmusic/cube-studio#234]
如题，点击
![image](https://github.com/tencentmusic/cube-studio/assets/60888073/e72c6f3d-1582-4f13-8d2b-4e1f8127fa2b)
以及
![image](https://github.com/tencentmusic/cube-studio/assets/60888073/511461a1-9c25-4053-9455-62ac6964f09b)
时，会出现404页面
![image](https://github.com/tencentmusic/cube-studio/assets/60888073/0697474f-207d-40de-8fec-03f75325b7ea)

**Comment by data-infra** [comment]
平台的入口为istio-ingressgateway，不是前端服务。并且如果从ip切换到域名，或者更改了域名，要修改gateway.yaml文件
