### ISSUE TITLE
单机部署 数据库可以用单独机器的数据库吗

### ISSUE THREAD

**Issue by hqfgithub** [tencentmusic/cube-studio#239]

**Comment by lkad** [comment]
可以，你把配置里面的数据库连接改一下就可以了，然后重启应用就会重新初始化数据库.install/kubernetes/cube/overlays/kustomization.yml 文件中 
- name: deploy-config
  literals:
  - STAGE=prod
  - REDIS_HOST=redis-master.infra
  - REDIS_PORT=6379
  - REDIS_PASSWORD=admin
  - MYSQL_SERVICE=mysql+pymysql://root:admin@mysql-service.infra:3306/kubeflow?charset=utf8
  - ENVIRONMENT=DEV
  - GPU_TYPE=NVIDIA
  这一段
