### ISSUE TITLE
更新了最新版后还是会拉取镜像失败

### ISSUE THREAD

**Issue by cyxnzb** [tencentmusic/cube-studio#25]
Failed to pull image "ai.tencentmusic.com/tme-public/notebook:jupyter-ubuntu-cpu-1.0.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for ai.tencentmusic.com/tme-public/notebook, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by cyxnzb** [comment]
我是先拉去了tme-dev版本，然后解压后sh pull_image_kubeflow.sh
kubectl delete -k cube/overlays
kubectl apply -k cube/overlays
但是还是会这样

**Comment by data-infra** [comment]
不要使用tme-dev版本，使用最新的master分支。

外部或内部仓库更换，主要体现在几个方面的更新。
1、平台基础组件镜像仓库更新。可以拉取最新代码install/kubernetes/下
pull_image_kubeflow.sh
kubectl delete -k cube/overlays
kubectl apply -k cube/overlays

2、平台发起的调度pod的镜像的更新，比如训练/notebook的镜像更新。同上第一步的更新配置已经更新了，但是还存在存量msyql元数据中的镜像的更新，可以进入数据库，手动批量修改其中的镜像。比如把仓库
ai.tencentmusic.com/tme-public/ 换成  ccr.ccs.tencentyun.com/cube-studio/

```
UPDATE docker SET base_image = replace (base_image,'ai.tencentmusic.com/tme-public','ccr.ccs.tencentyun.com/cube-studio') WHERE args LIKE '%tencentmusic%'

UPDATE images SET name = replace (name,'ai.tencentmusic.com/tme-public','ccr.ccs.tencentyun.com/cube-studio') WHERE args LIKE '%tencentmusic%'

UPDATE inferenceservice SET images = replace (images,'ai.tencentmusic.com/tme-public','ccr.ccs.tencentyun.com/cube-studio') WHERE args LIKE '%tencentmusic%'

UPDATE service SET images = replace (images,'ai.tencentmusic.com/tme-public','ccr.ccs.tencentyun.com/cube-studio') WHERE args LIKE '%tencentmusic%'

UPDATE notebook SET images = replace (images,'ai.tencentmusic.com/tme-public','ccr.ccs.tencentyun.com/cube-studio') WHERE args LIKE '%tencentmusic%'

UPDATE task SET args = replace (args,'ai.tencentmusic.com/tme-public','ccr.ccs.tencentyun.com/cube-studio') WHERE args LIKE '%tencentmusic%'

```

**Comment by cyxnzb** [comment]
好滴，我应该是第二块出现了问题

**Comment by cyxnzb** [comment]
UPDATE docker SET base_image = replace (base_image,'ai.tencentmusic.com/tme-public','ccr.ccs.tencentyun.com/cube-studio') WHERE args LIKE '%tencentmusic%'

**Comment by cyxnzb** [comment]
这个是哪个库的

**Comment by longlimin** [comment]
我也遇到拉取镜像失败问题，可通过手工拉取源镜像，然后推送到自己搭建的harbor中去，然后使用自建harbor拉取，此方法可以解决镜像拉取问题。
