### ISSUE TITLE
rancher 创建失败，等了好久还不成功

### ISSUE THREAD

**Issue by flysky2008** [tencentmusic/cube-studio#28]
#16
<img width="519" alt="20220616071110" src="https://user-images.githubusercontent.com/46547923/173957220-81c12179-15c9-4c09-a499-2a572ad83842.png">

**Comment by flysky2008** [comment]
> 凭我这个月摸索的经验，应该是rancher环境没清理干净，每次尝试部署前一定先清理彻底

有清理的脚本吗？尝试很多目前还没解决

**Comment by longlimin** [comment]
可以尝试用rancher最新的版本，新版本能避免不少错误。  docker run -d --privileged --restart=unless-stopped  -p 443:443   rancher/rancher

**Comment by data-infra** [comment]
1、先把rancher镜像拉取下来，省的创建的时候等待久，以为不成功。
2、如果还是有问题，就先sh reset_docker.sh，然后查看docker ps，是否已经清空干净，如果不干净，就重启机器后在reset_docker.sh，  docker ps没有容器了才说明清理干净
3、重新执行docker run，如果还是不行，多试几次，还有换大一点的机器，>8核，16G
4、如果已经部署过，但是突然rancher web界面打不开了，日志报等待k3s启动错误，那就按照[单机高可用方案](https://github.com/tencentmusic/cube-studio/wiki/%E4%BD%BF%E7%94%A8rancher%E8%87%AA%E5%BB%BAk8s%E9%9B%86%E7%BE%A4#%E5%8D%95%E8%8A%82%E7%82%B9%E7%9A%84%E9%85%8D%E7%BD%AE%E9%AB%98%E5%8F%AF%E7%94%A8)
