### ISSUE TITLE
在平台部署notebook直接提示unkown,选择reset会报错

### ISSUE THREAD

**Issue by cyxnzb** [tencentmusic/cube-studio#29]
版本是2022年6月16日凌晨拉的master分支最新版本
单机部署
在k8s看所有节点状态正常
操作触发条件：
{
 1.创建新的notebook项目
 2.发现状态unkown后，点击reset触发
}
![微信图片_20220616090308](https://user-images.githubusercontent.com/51886383/173969961-b2cf9092-15f2-42e6-953d-c0e33a2b0d11.png)
![微信图片_20220616090637](https://user-images.githubusercontent.com/51886383/173970014-19f30a82-0441-4e71-b661-af338f5e1df8.png)
![微信图片_20220616090645](https://user-images.githubusercontent.com/51886383/173970028-48866fe7-43ed-454a-a5f4-c84b0a0798df.png)
点击“名称”直接提示404页面

**Comment by cyxnzb** [comment]
rancher版本是latest版本，即2.6.3

**Comment by cyxnzb** [comment]
解决了，昨晚自行部署的时候，网络波动断开了与服务器的连接导致后续有些没有执行成功

**Comment by zhuqiming678** [comment]
有时候那个用户名包含特殊字符也不行，需要修改用户名。。
