### ISSUE TITLE
在jupyter lab中加入大数据功能

### ISSUE THREAD

**Issue by xiaodin1** [tencentmusic/cube-studio#3]
是否有计划在jupyter lab中加入大数据处理spark组件呢？通过livy server打通数据交换的流程。

p.s.如何加入你们开发呢？

**Comment by kalenhaha** [comment]
目前因为人力原因暂时未有计划加入Spark组件, 但是欢迎其他有意向的同学来添加相关组件. 有意向进行开源共建的同学请微信添加767065521并备注"Cube Studio开源共建"进入微信群.

**Comment by kalenhaha** [comment]
> 是否有计划在jupyter lab中加入大数据处理spark组件呢？通过livy server打通数据交换的流程。
> 
> p.s.如何加入你们开发呢？

目前因为人力原因暂时未有计划加入Spark组件, 但是欢迎其他有意向的同学来添加相关组件. 有意向进行开源共建的同学请微信添加767065521并备注"Cube Studio开源共建"进入微信群.
