### ISSUE TITLE
总有一个镜像拉取有问题是为什么？

### ISSUE THREAD

**Issue by Bay-lynduner** [tencentmusic/cube-studio#30]
Error response from daemon: Head "https://ccr.ccs.tencentyun.com/v2/cube-studio/mpioperator-kubectl-delivery/manifests/latest": unauthorized: authentication required.
这是为什么？

**Comment by Bay-lynduner** [comment]
别的镜像都能拉取，就这一个报错，没权限？

**Comment by data-infra** [comment]
已放开仓库权限。
