### ISSUE TITLE
能否提供如何部署triton-server的教程

### ISSUE THREAD

**Issue by wuqingzhou828** [tencentmusic/cube-studio#31]

**Comment by qianchen94** [comment]
同求一个tf-serving的... ...

**Comment by wuqingzhou828** [comment]
> https://github.com/tencentmusic/cube-studio/wiki <img alt="image" width="593" src="https://user-images.githubusercontent.com/20157705/176401347-84d2f772-664b-4d40-9b97-cb8a55e2a522.png">
部署成功之后：triton_client_url？model_name=？
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/13218022/177120874-dba79f96-7d46-4b55-b080-be0eb28cb303.png">
triton_client_url=？
model_name=？
try:
    triton_client = grpcclient.InferenceServerClient(
        url=triton_client_url,
        verbose=False,
        ssl=False)
    res = triton_client.is_model_ready(model_name=model_name)
    print("channel creation sucess .\n")
    print(res)
except Exception as e:
    print("channel creation failed: " + str(e) + "\n")
