### ISSUE TITLE
请问，多机器部署的时候，worker需不需要运行start.sh？

### ISSUE THREAD

**Issue by Bay-lynduner** [tencentmusic/cube-studio#34]
以前单机部署已经没问题了，我现在我在尝试集群部署，结果master运行start.sh后集群爆了一堆错

我目前的理解是不需要，不知道对不对

**Comment by Bay-lynduner** [comment]
报错信息都是： ReplicaSet “xxxxxxxxxxxxxx” has timed out progressing..

**Comment by Bay-lynduner** [comment]
还有一个问题，label都是在start.sh这个脚本里头，如果不运行它怎么通过label来管理机器呢？

**Comment by cyxnzb** [comment]
> 还有一个问题，label都是在start.sh这个脚本里头，如果不运行它怎么通过label来管理机器呢？

单独拉出来不知道行不行，你可以试试，其实还是调用的kubectl的命令吧（个人猜测，不一定对

**Comment by Bay-lynduner** [comment]
> 

唉，没有多机部署指南，对不太熟悉k8s的人不友好。。。

**Comment by cyxnzb** [comment]
> > 
> 
> 唉，没有多机部署指南，对不太熟悉k8s的人不友好。。。
https://github.com/tencentmusic/cube-studio/tree/master/install/kubernetes#%E9%83%A8%E7%BD%B2-%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0
这个你可以参考下，不过确实需要一定的k8s基础，因为它是基于k8s的，所以可以试试单机部署熟悉一下整体环境

**Comment by zhuyaguang** [comment]
同问，多机部署不执行start.sh 那服务怎么部署多

**Comment by data-infra** [comment]
start.sh 是在当前k8s集群部署 cube平台的。 如果还是在同一个k8s集群，只是增加了机器，是不需要再执行start.sh的。只需要把机器加入到已经存在的k8s集群就行了

**Comment by zhuyaguang** [comment]
所以 我理解多机部署是在单机部署基础上，扩容新的节点，实现多机部署。

**Comment by data-infra** [comment]
> 所以 我理解多机部署是在单机部署基础上，扩容新的节点，实现多机部署。

是的
