### ISSUE TITLE
单集群多机 一直卡在Waiting to register with Kubernetes

### ISSUE THREAD

**Issue by wuqingzhou828** [tencentmusic/cube-studio#35]
https://github.com/tencentmusic/cube-studio/wiki/%E5%A4%9A%E6%9C%BA%E3%80%81%E5%A4%9A%E9%9B%86%E7%BE%A4%E3%80%81%E5%A4%9A%E9%A1%B9%E7%9B%AE%E7%BB%84-%E9%83%A8%E7%BD%B2%E8%B0%83%E5%BA%A6
按这个wiki 单集群多机 添加的worker节点

**Comment by aeeeeeep** [comment]
你好，我也遇到了这个问题，请问你是如何解决的
