### ISSUE TITLE
请教一下各位大牛，能不能大概说一下master节点打哪些服务的label，worker上又是哪些label是true？

### ISSUE THREAD

**Issue by Bay-lynduner** [tencentmusic/cube-studio#36]
刚接触k8s，多机器部署不来呀。。

**Comment by cyxnzb** [comment]
根据所需吧
通过label进行机器管理
开发训练服务机器管理：

对于cpu的train/notebook/service会选择cpu=true的机器

对于gpu的train/notebook/service会选择gpu=true的机器

训练任务会选择train=true的机器

notebook会选择notebook=true的机器

服务化会选择service=true的机器

不同项目的任务会选择对应org=xx的机器。默认为org=public

可以通过gpu-type=xx表示gpu的型号

控制器机器管理：

mysql=true 部署mysql服务的机器
redis=true 部署mysql服务的机器
kubeflow-dashobard=true 部署cube服务的机器
kubeflow=true 部署kubeflow的机器
isito=true 部署istio的机器
knative=true 部署knative的机器
monitoring=true 部署prometheus的机器

参考:https://github.com/tencentmusic/cube-studio/tree/master/install/kubernetes#%E9%80%9A%E8%BF%87label%E8%BF%9B%E8%A1%8C%E6%9C%BA%E5%99%A8%E7%AE%A1%E7%90%86

**Comment by wuqingzhou828** [comment]
woker :
kubectl label node worker0 train=true cpu=true gpu=true gpu-type=V100 notebook=true service=true org=public --overwrite

**Comment by Bay-lynduner** [comment]
> woker : kubectl label node worker0 train=true cpu=true gpu=true gpu-type=V100 notebook=true service=true org=public --overwrite

请问你有没有部署成功的案例？如果你成功了能不能把你的master和worker的标签都告诉我怎么设置呢？我不想再去花时间在这方面试错了

**Comment by wuqingzhou828** [comment]
> > woker : kubectl label node worker0 train=true cpu=true gpu=true gpu-type=V100 notebook=true service=true org=public --overwrite
> 
> 请问你有没有部署成功的案例？如果你成功了能不能把你的master和worker的标签都告诉我怎么设置呢？我不想再去花时间在这方面试错了
kubectl label node master train=true cpu=true gpu=true gpu-type=V100 notebook=true service=true org=public istio=true knative=true kubeflow=true kubeflow-dashboard=true mysql=true redis=true monitoring=true logging=true --overwrite


kubectl label node worker0 train=true cpu=true gpu=true gpu-type=V100 notebook=true service=true org=public --overwrite
