### ISSUE TITLE
！！metric-server默认镜像拉取是Always，然后在rancher中修改不动yaml文件是怎么回事？

### ISSUE THREAD

**Issue by Bay-lynduner** [tencentmusic/cube-studio#39]
![image](https://user-images.githubusercontent.com/52901655/174994496-d7e46fca-6328-4b4a-b599-99e517d09da9.png)

能不能来个人教一下怎么修改？卡我一天了。。

**Comment by data-infra** [comment]
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/20157705/175022827-80c0113c-2656-417c-a3c1-1df820b1d125.png">
rancher里面是这样修改的
