### ISSUE TITLE
所有服务都没问题了，可是输入本机ip还是进的rancher，死活进不去cube的界面，怎么破？

### ISSUE THREAD

**Issue by Bay-lynduner** [tencentmusic/cube-studio#40]

**Comment by Bay-lynduner** [comment]
运行kubectl get service -A命令发现：
    kubeflow-dashboard 的TYPE 一直都是Cluster IP
    怎样才能进入cube的前端页面？

**Comment by data-infra** [comment]
https://本机ip   是rancher界面
http://本机ip   是cube界面

只暴露一个服务，istio-system命名空间的istio-ingressgateway服务。

**Comment by Bay-lynduner** [comment]
> [https://本机ip](https://%E6%9C%AC%E6%9C%BAip) 是rancher界面 [http://本机ip](http://%E6%9C%AC%E6%9C%BAip) 是cube界面
> 
> 只暴露一个服务，istio-system命名空间的istio-ingressgateway服务。

嘿嘿嘿....

**Comment by zzzzzzyzz** [comment]
我也是这个问题，但是访问http:ip还是进不去
只暴露一个服务，istio-system命名空间的istio-ingressgateway服务。

**Comment by data-infra** [comment]
参考wiki，“单机部署”，文章尾部，有排查流程
