### ISSUE TITLE
can add claimRef in PV？

### ISSUE THREAD

**Issue by zhuyaguang** [tencentmusic/cube-studio#48]
pv can not Bound to pvc ,add claimRef can solve it !

sometime i add  `storageClassName: local` in pv,but Sometimes it works, sometimes it doesn't, I'm confused。

![image](https://user-images.githubusercontent.com/8857976/179641383-0edba226-e0d4-4d2b-9970-48e45b0becca.png)

**Comment by data-infra** [comment]
pv和pvc的自定绑定有几个配置控制。
1、pvc中selector与pv的label相互对应，pv的大小满足pvc的大小需求，这个在开源方案里面是配置好的。
2、重新部署时pv的状态，是不是available状态。不然pvc无法绑定到pv上，需要删除pv中心部署pv
3、部分平台上会自动在pvc中自动添加storage class，造成pv不适配pvc，需要在pv中也添加相同storage class
