### ISSUE TITLE
 some namespaces without pods 

### ISSUE THREAD

**Issue by zhuyaguang** [tencentmusic/cube-studio#49]
in create_ns_secret.sh
for namespace in 'infra' 'kubeflow' 'istio-system' 'knative-serving' 'pipeline' 'katib' 'jupyter' 'kfserving' 'service' 'pre-service' 'cert-manager' 'monitoring' 'logging' 'kube-system' 'volcano-system'

`katib jupyter kfserving pre-service  cert-manager logging `

this namespaces without pods

**Comment by data-infra** [comment]
katib命名空间是用来所有类型的超参搜索组件

**Comment by data-infra** [comment]
新版本做了优化，去除了部分命名空间，新版本：
istio-system：sitio网关和控制面
kubeflow：nni/frameworkcontrolle，kfp/argo，training-operator/spark-operator/paddle-controller-manager，volcano
monitoring：监控体系
infra：cube-studio组件
pipeline：用户任务
service：用户服务
jupyter：用户notebook
automl：用户automl任务
