### ISSUE TITLE
少一个镜像ra:latest

### ISSUE THREAD

**Issue by VincentWei2021** [tencentmusic/cube-studio#5]
docker pull ai.tencentmusic.com/tme-public/ra:latest

**Comment by data-infra** [comment]
似乎没有找到这个镜像

**Comment by VincentWei2021** [comment]
rancher/all_image.py
![image](https://user-images.githubusercontent.com/77832074/169957736-8343e06f-3ffd-40e6-bb48-9088032759a3.png)

**Comment by data-infra** [comment]
fix https://github.com/tencentmusic/cube-studio/blob/master/install/kubernetes/rancher/all_image.py
