### ISSUE TITLE
core-dns出错，service name无法解析，集群启动，但是pod之间无法通信，是什么原因

### ISSUE THREAD

**Issue by exquisite2007** [tencentmusic/cube-studio#51]
集群是单节点集群，根据B站视屏安装
安装后，k8s启动，只是pod之间，pod与service无法通信
![image](https://user-images.githubusercontent.com/6326364/180740747-58f050d7-e241-400a-8b7a-4ec7ab4b60fc.png)
![image](https://user-images.githubusercontent.com/6326364/180740846-69381af7-8dae-4c45-a897-0d73e90b5bcb.png)
建立集群的时候，尝试过flannel和calico，都是这个状态
这个是什么原因？
或者该怎么排查？

**Comment by data-infra** [comment]
在腾讯云机器上部署可能会存在这样的任务。主要是kube-system命名空间下的core-dns不正常。可能的原因
1、主机上53端口占用，比如主机携带bind服务，会占用了53端口，造成coredns无法启动。需要关注主机本身的dns服务
2、主机域名服务器中有127.0.0.1，无法启动。修正主机`/etc/resolv.conf`目录下的dns服务器配置，并重启 `docker restart kubelet`
3、coredns的资源limit太小，可以把resource limit去掉
4、防火墙限制，虽然在云上有安全组限制，但是在主机上可能还有一层防火墙的限制。iptables 放开dns。`/sbin/iptables -P FORWARD ACCEPT`


正常的 日志应该是这样的
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/20157705/180744292-8878ab23-3b94-4bbb-b0eb-0facc6a833eb.png">

**Comment by exquisite2007** [comment]
> 虽然在云上有安全组限制，但是在主机上可能还有一层防火墙的限制。iptables

多谢@data-infra回复
我的部署不在腾讯云，是我司内部的一个云主机。
这个应该和core-dns没关系，core-dns启动正常，core-dns只影响service。但我验证了直接对同一个namespace的两个pod都ping不通
![image](https://user-images.githubusercontent.com/6326364/180750508-12120986-00fb-48ed-947c-661ce38bc4df.png)
如下图，我进入了volcano-admission-85b7ccb489-cztl2这个pod 去ping 10.42.119.73 是不通的
![image](https://user-images.githubusercontent.com/6326364/180750894-d609655c-07de-4004-8443-fc091a71b0f5.png)

ping主机ip可通
![image](https://user-images.githubusercontent.com/6326364/180751403-3abe3eee-8667-49f4-a341-c7f81266a931.png)

**Comment by data-infra** [comment]
rancher k8s使用的是nat网络模式，本身就无法响应ping命令。只能通过ping服务名看看能不能解析出服务名的ip。不会有ping响应。

**Comment by exquisite2007** [comment]
这个是coredns日志，无法访问公有dns，有解吗？
![image](https://user-images.githubusercontent.com/6326364/180904629-0f162cd6-2e4d-4b36-973e-fefdfbf5ef12.png)

**Comment by data-infra** [comment]
试试   `/sbin/iptables -P FORWARD ACCEPT`

**Comment by exquisite2007** [comment]
> 

是这个原因，多谢@data-infra
