### ISSUE TITLE
dataset+job-template+pipeline+inference  demo

### ISSUE THREAD

**Issue by cdllp2** [tencentmusic/cube-studio#61]
视觉：yolo相关模型、darknet相关模型、PaddleSeg 图像分割，orc相关模型，等训练和推理支持

语音：wenet语音识别的训练和推理支持。

推荐：bin算法，deepfm，ple等算法的训练和推理服务支持

文本： bert框架模型的训练和推理支持

**Comment by data-infra** [comment]
新版本会初始化使用示例
