### ISSUE TITLE
持续了好久，然后报了这个错误

### ISSUE THREAD

**Issue by ZXTFINAL** [tencentmusic/cube-studio#77]
![image](https://user-images.githubusercontent.com/53009474/187857531-63fb325e-ca59-4657-b7c5-a23d8fed5ed5.png)

**Comment by cyxnzb** [comment]
等待片刻也无果吗

**Comment by deerandsea** [comment]
看下k8s报错呢

**Comment by ZXTFINAL** [comment]
> 看下k8s报错呢

![image](https://user-images.githubusercontent.com/53009474/188355714-6dfc775f-14fb-4abb-bd2b-d91155e5d7eb.png)

**Comment by ZXTFINAL** [comment]
问题解决了，因为服务器之前有安装snap的minik8s,环境不干净
