### ISSUE TITLE
K8S高版本的支持

### ISSUE THREAD

**Issue by hooping** [tencentmusic/cube-studio#78]
看到文档中提到kubernetes = 1.18。社区中讨论看到说对1.20也可以支持。
https://github.com/tencentmusic/cube-studio/wiki/%E5%B9%B3%E5%8F%B0%E5%8D%95%E6%9C%BA%E9%83%A8%E7%BD%B2

对于高版本的支持如何？比如1.22， 1.23一直到1.25的支持？thanks.

**Comment by cyxnzb** [comment]
1.24.4我这边是出现pods全绿但是访问不了平台

**Comment by data-infra** [comment]
目前已经支持到k8s 1.21，1.22

**Comment by data-infra** [comment]
目前支持到k8s 1.23，1.24
