### ISSUE TITLE
关于start.sh一些补充的东西

### ISSUE THREAD

**Issue by ZXTFINAL** [tencentmusic/cube-studio#79]
`bash init_node.sh
mkdir ~/.kube && cp config ~/.kube/config
mkdir kubeconfig && echo "" > kubeconfig/dev-kubeconfig
curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl && chmod +x kubectl  && cp kubectl /usr/bin/ && mv kubectl /usr/local/bin/`
这是前几段的指令，我在部署时发现kubectl会去检测 /etc/kubernetes/admin.conf是否存在
建议添加`cp ~/.kube/config /etc/kubernetes/admin.conf`

**Comment by cyxnzb** [comment]
确实，之前我有时候查节点情况的时候，也会手动cp过去一个

**Comment by data-infra** [comment]
fix

**Comment by ZhenpengChenCode** [comment]
@ZXTFINAL 你好，"cp config ~/.kube/config"，这里的config文件从哪里获得？
