### ISSUE TITLE
关于自己写的服务进行部署的问题

### ISSUE THREAD

**Issue by ZXTFINAL** [tencentmusic/cube-studio#80]
我使用notebook在/mnt/admin下写了一个flask服务，然后自己从自己的私有仓库建立了个镜像如图
![image](https://user-images.githubusercontent.com/53009474/190091447-575fc6dd-953b-4759-a9e3-9755e96c363d.png)
![image](https://user-images.githubusercontent.com/53009474/190091515-cd72a145-66b3-48a7-a550-36aa586e9ace.png)
随后我在工作流里这样设置
![image](https://user-images.githubusercontent.com/53009474/190091712-1d24d30c-7732-4836-970c-e1aa5c388c41.png)
运行之后，实例显示运行成功，看了源码其实是调用服务部署的接口即
![image](https://user-images.githubusercontent.com/53009474/190092155-8e589b7e-d24e-49c4-a59c-7336c17ab4a1.png)
点击模型部署生产后无法进行容器的访问
![image](https://user-images.githubusercontent.com/53009474/190092382-fd583329-b220-461f-a099-0791c44501a9.png)
后台检查容器，貌似没有按照既有的方式起容器，这是怎么回事呢 @data-infra

**Comment by ZXTFINAL** [comment]
另外，使用示例的yolov3服务是可以正常访问的，只是自己写的服务镜像无法访问，我理解满足启动条件的镜像挂载了/mnt/admin路径，开放了端口，应该可以启动才对

**Comment by ZXTFINAL** [comment]
这个镜像也是通过官方的构建方式构建的
![image](https://user-images.githubusercontent.com/53009474/190094160-50eea309-b6b2-4c94-b943-f1adabf65314.png)
仓库里也确认push成功了
![image](https://user-images.githubusercontent.com/53009474/190094261-a84b03e3-19d3-464c-bd4f-f7157f7bf345.png)

**Comment by ZXTFINAL** [comment]
容器内也没有任何日志
![image](https://user-images.githubusercontent.com/53009474/190094868-4a6e3c8d-bf99-40a6-a7cd-41dc0ca166e1.png)

**Comment by ZXTFINAL** [comment]
调试时显示
![image](https://user-images.githubusercontent.com/53009474/190095627-9eaacfb8-295a-4275-928b-8ae623022992.png)

**Comment by ZXTFINAL** [comment]
pod日志为
container "test" in pod "test-5c7658cbf7-ww6wx" is waiting to start: trying and failing to pull image

**Comment by data-infra** [comment]
能正常拉取内网仓库
1、对于https仓库，需要在仓库里面配置账号密码
2、对于http仓库，还需要在机器上docker里面配置允许的非安全仓库

**Comment by ZXTFINAL** [comment]
> 能正常拉取内网仓库 1、对于https仓库，需要在仓库里面配置账号密码 2、对于http仓库，还需要在机器上docker里面配置允许的非安全仓库

已经设置过了，在服务器可以拉取仓库内的镜像
![image](https://user-images.githubusercontent.com/53009474/190324705-35771569-b263-486d-9419-9aa9c9a5d2c8.png)
![image](https://user-images.githubusercontent.com/53009474/190324804-04fa51dd-2f81-4ddf-b3de-1dbe5ba2ec51.png)
平台上镜像构建push能push上去，pull好像一直失败，这块是写在哪里的呢

**Comment by data-infra** [comment]
可以在k8s dashboard 界面上看到 为啥拉取失败，反推哪里的问题

**Comment by ZXTFINAL** [comment]
> 可以在k8s dashboard 界面上看到 为啥拉取失败，反推哪里的问题

重新设置了仓库信息好了，感谢
