### ISSUE TITLE
单机部署平台，或许是本地虚拟机资源不足引起的服务部署不全？connection refused

### ISSUE THREAD

**Issue by Bay-lynduner** [tencentmusic/cube-studio#82]
运行start.sh，最后一大段显示为：
![image](https://user-images.githubusercontent.com/52901655/190392439-02ad3780-69f3-4569-b931-c3fc3d6d2fd6.png)
![image](https://user-images.githubusercontent.com/52901655/190392548-9fd3eebb-25c3-4450-9339-e573e5ab39a2.png)
![image](https://user-images.githubusercontent.com/52901655/190392639-3d32c7c0-ad0e-471d-ae9d-6d01febc633d.png)

**Comment by Bay-lynduner** [comment]
很明显服务部署不全。
![image](https://user-images.githubusercontent.com/52901655/190393946-39c7246d-001f-41c5-ab9b-6c87ed0b1443.png)
。。。。。。

顺带问一下cube平台的前端页面所依赖的镜像是哪一个？叫什么？

**Comment by data-infra** [comment]
组件说明：
https://github.com/tencentmusic/cube-studio/wiki/%E5%9F%BA%E7%A1%80%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D

**Comment by ZXTFINAL** [comment]
是你kubectl的问题，它访问不到一些配置文件，可以看我的issue #79

**Comment by ZXTFINAL** [comment]
> 可以参考下： https://www.jianshu.com/p/6edc9f171df1

盲猜就是/etc/kubernetes/admin.conf没有的问题

**Comment by ZXTFINAL** [comment]
> 很明显服务部署不全。 ![image](https://user-images.githubusercontent.com/52901655/190393946-39c7246d-001f-41c5-ab9b-6c87ed0b1443.png) 。。。。。。
> 
> 顺带问一下cube平台的前端页面所依赖的镜像是哪一个？叫什么？

前几步只是在复制配置文件，所有安装的部分都因为kubectl的问题没有成功

**Comment by cyxnzb** [comment]
> > 可以参考下： https://www.jianshu.com/p/6edc9f171df1
> 
> 盲猜就是/etc/kubernetes/admin.conf没有的问题

但是有点奇怪，因为最新版本的start.sh里面已经有cp admin.conf的代码了，所以应该不会出现这个问题呀，我感觉可能他用的是较早的版本？

**Comment by ZXTFINAL** [comment]
> > > 可以参考下： https://www.jianshu.com/p/6edc9f171df1
> > 
> > 
> > 盲猜就是/etc/kubernetes/admin.conf没有的问题
> 
> 但是有点奇怪，因为最新版本的start.sh里面已经有cp admin.conf的代码了，所以应该不会出现这个问题呀，我感觉可能他用的是较早的版本？

毕竟最近才改

**Comment by Bay-lynduner** [comment]
> > > 可以参考下： https://www.jianshu.com/p/6edc9f171df1
> > 
> > 
> > 盲猜就是/etc/kubernetes/admin.conf没有的问题
> 
> 但是有点奇怪，因为最新版本的start.sh里面已经有cp admin.conf的代码了，所以应该不会出现这个问题呀，我感觉可能他用的是较早的版本？

我用的是8月份的release版本，cp admin.conf是最新的master代码吗？

**Comment by Bay-lynduner** [comment]
> > > > 可以参考下： https://www.jianshu.com/p/6edc9f171df1
> > > 
> > > 
> > > 盲猜就是/etc/kubernetes/admin.conf没有的问题
> > 
> > 
> > 但是有点奇怪，因为最新版本的start.sh里面已经有cp admin.conf的代码了，所以应该不会出现这个问题呀，我感觉可能他用的是较早的版本？
> 
> 毕竟最近才改

不对啊，我检查了我的start.sh，有cp admin.conf，8月份的release版

**Comment by Bay-lynduner** [comment]
> 组件说明： https://github.com/tencentmusic/cube-studio/wiki/%E5%9F%BA%E7%A1%80%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D

查看了pull_image_kubeflow.sh，没有发现拉取kubeflow-dashboard的语句呀
