### ISSUE TITLE
页面有些功能不可点击

### ISSUE THREAD

**Issue by lzt123123** [tencentmusic/cube-studio#96]
页面上有些功能处于不可点击状态，请问这些功能是还在开发中还是有另外完整的一套商业版呢，盼回复
![image](https://user-images.githubusercontent.com/43226215/193875468-0c82d6ec-3994-4174-bad4-f379f3fb9369.png)
![image](https://user-images.githubusercontent.com/43226215/193875569-fb79618e-37f8-481f-ad37-072039c0ff21.png)
![image](https://user-images.githubusercontent.com/43226215/193875602-ba5740c6-f1ed-4792-80dd-4cf857ebdecc.png)
![image](https://user-images.githubusercontent.com/43226215/193875686-28528cec-03b0-46c6-b1b9-52bf381d2175.png)

**Comment by cyxnzb** [comment]
有些功能应当是在开发中，也可以自行进行对接

**Comment by lzt123123** [comment]
> 应该是在开发中，功能也可以自己进行对接

具体怎么对接呢

**Comment by data-infra** [comment]
目前在企业版中才可以使用
