### ISSUE TITLE
在notebook到期后，进行reset，会出现404

### ISSUE THREAD

**Issue by cyxnzb** [tencentmusic/cube-studio#97]
具体如下：
假如我的平台部署在xxx.com下，然后我通过xxx.com,对已到期的的notebook进行续期，之后整个平台都会404，只能通过ip访问平台，然后续期（即reset)会重新拉pod，拉完后访问会出现404，必须再拉一次才可以

**Comment by data-infra** [comment]
是因为混用了域名和ip，使用域名需要修改gateway.yaml中的配置，可以看yaml文件中的描述
